'use client'

import { FormEvent, useMemo, useState } from 'react'
import { ArrowLeft, ArrowUp, Check, ChevronRight, Copy, KeyRound, Menu, MoreHorizontal, Paperclip, Phone, QrCode, Search, Settings, Sparkles, Sun, UserRound, Video, X } from 'lucide-react'

type Contact = { name: string; alias: string; snippet: string; time: string; online: boolean; emoji: string }
const contacts: Contact[] = [
  { name: 'Morgan Lee', alias: '@morgan', snippet: 'The violet room is ready.', time: '09:42', online: true, emoji: 'M' },
  { name: 'Sage Chen', alias: '@sage', snippet: 'Sending you the notes now.', time: 'Yesterday', online: true, emoji: 'S' },
  { name: 'Riley Park', alias: '@riley', snippet: 'That sounds like a plan.', time: 'Tue', online: false, emoji: 'R' },
  { name: 'Noah Williams', alias: '@noah', snippet: 'Let’s talk after sunset.', time: 'Mon', online: true, emoji: 'N' },
]
const stories = [{ name: 'Morgan', emoji: 'M', active: true }, { name: 'Sage', emoji: 'S', active: true }, { name: 'Riley', emoji: 'R', active: false }, { name: 'Noah', emoji: 'N', active: true }]
const seed = ['velvet','orbit','cinder','lumen','quiet','violet','harbor','north','echo','silver','morrow','atlas']

function Mark() { return <span className="brand-mark"><Sparkles /></span> }
function Gateway({ onEnter }: { onEnter: () => void }) {
  const [generated, setGenerated] = useState(false); const [revealed, setRevealed] = useState(false)
  return <main className="gateway"><div className="gateway-art"><div className="gateway-ring" /><div className="gateway-mark"><Mark /></div></div><span className="eyebrow">PRIVATE MESSENGER / 01</span><h1>Find your people.<br /><em>Keep your space.</em></h1><p className="gateway-copy">Nexus is a quiet, cryptographic room for the people who matter. No feeds. No noise. Just presence.</p>{!generated ? <button className="primary-action" onClick={() => setGenerated(true)}><KeyRound /> Generate your private identity <ChevronRight /></button> : <div className="identity-card"><div className="identity-card-head"><span>YOUR PRIVATE SEED</span><button onClick={() => setRevealed(!revealed)}>{revealed ? 'Mask' : 'Reveal'}</button></div><div className="seed-words">{seed.map((word, i) => <span key={word}>{revealed ? `${i + 1}. ${word}` : `${String(i + 1).padStart(2,'0')} •••••`}</span>)}</div><button className="primary-action" onClick={onEnter}>Enter Nexus Network <ArrowUp /></button></div>}<small className="gateway-note">Your identity is generated on-device and never stored by Nexus.</small></main>
}
function Directory({ onSelect, onSettings }: { onSelect: (contact: Contact) => void; onSettings: () => void }) { return <main className="messenger-shell"><header className="messenger-header"><button className="nav-icon" aria-label="Open menu"><Menu /></button><div className="brand-lockup"><Mark /><b>NEXUS</b></div><div className="header-actions"><button className="nav-icon" onClick={onSettings} aria-label="Open settings"><Settings /></button><button className="nav-icon" aria-label="More options"><MoreHorizontal /></button></div></header><div className="directory-head"><div><span className="eyebrow">PRIVATE NETWORK</span><h1>Your people<span>.</span></h1></div><button className="profile-orb" aria-label="Your profile"><UserRound /></button></div><div className="search-bar"><Search /><input placeholder="Search your network" /></div><section className="stories"><div className="section-label"><span>Stories</span><button>View all</button></div><div className="story-row">{stories.map((story) => <button className="story" key={story.name}><span className={`story-avatar ${story.active ? 'story-active' : ''}`}>{story.emoji}</span><small>{story.name}</small></button>)}</div></section><section className="contacts"><div className="section-label"><span>Conversations</span><span className="muted">{contacts.length} people</span></div>{contacts.map((contact) => <button className="contact-row" key={contact.name} onClick={() => onSelect(contact)}><span className={`contact-avatar ${contact.online ? 'online' : ''}`}>{contact.emoji}</span><span className="contact-copy"><b>{contact.name}</b><small>{contact.alias} · {contact.snippet}</small></span><span className="contact-meta"><small>{contact.time}</small><ChevronRight /></span></button>)}</section><footer className="network-footer"><span className="online-dot" /> Encrypted network <span>·</span> 12 peers</footer></main> }
function Chat({ contact, onBack, onSettings }: { contact: Contact; onBack: () => void; onSettings: () => void }) { const [draft, setDraft] = useState(''); const [messages, setMessages] = useState(['Good morning. I left a little space here for you.', 'I like that. Let’s make today feel intentional.']); function submit(e: FormEvent) { e.preventDefault(); if (!draft.trim()) return; setMessages([...messages, draft.trim()]); setDraft('') } return <main className="messenger-shell chat-shell"><header className="chat-header"><button className="nav-icon" onClick={onBack} aria-label="Back"><ArrowLeft /></button><span className={`chat-avatar ${contact.online ? 'online' : ''}`}>{contact.emoji}</span><div className="chat-title"><b>{contact.name}</b><small>{contact.online ? 'online now' : 'last seen recently'}</small></div><div className="header-actions"><button className="nav-icon" aria-label="Start video call"><Video /></button><button className="nav-icon" onClick={onSettings} aria-label="Settings"><MoreHorizontal /></button></div></header><div className="chat-transcript"><div className="date-stamp"><span /> TODAY <span /></div>{messages.map((message, i) => <div className={`chat-message ${i % 2 ? 'mine' : ''}`} key={`${message}-${i}`}><p>{message}</p><small>{i % 2 ? '09:41 · Sent' : '09:40'}</small></div>)}<div className="typing"><span /> {contact.name} is in the room</div></div><div className="chat-composer-wrap"><div className="chat-tools"><button aria-label="Attach file"><Paperclip /></button><span>Private message</span><button aria-label="Start call"><Phone /></button></div><form className="chat-composer" onSubmit={submit}><input value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="Say something true..." /><button className="send-orb" aria-label="Send message"><ArrowUp /></button></form><small className="composer-note">End-to-end encrypted · ephemeral by default</small></div></main> }
function SettingsSheet({ onClose }: { onClose: () => void }) { return <div className="settings-sheet" role="dialog" aria-modal="true"><div className="sheet-panel"><header><div><span className="eyebrow">NEXUS / CONTROL</span><h2>Private settings</h2></div><button className="nav-icon" onClick={onClose} aria-label="Close settings"><X /></button></header><section><KeyRound /><div><b>Identity capsule</b><small>ed25519 · local-only identity</small></div><button className="sheet-button"><QrCode /> QR</button></section><section><Sun /><div><b>Afternoon light</b><small>Keep the room bright and clear</small></div><button className="switch"><i /></button></section><section><Copy /><div><b>Copy public alias</b><small>@alex · ready to share</small></div><button className="sheet-button"><Check /></button></section></div></div> }
export default function Page() { const [entered, setEntered] = useState(false); const [selected, setSelected] = useState<Contact | null>(null); const [settings, setSettings] = useState(false); const view = useMemo(() => selected ? <Chat contact={selected} onBack={() => setSelected(null)} onSettings={() => setSettings(true)} /> : <Directory onSelect={setSelected} onSettings={() => setSettings(true)} />, [selected]); return <div className="app-canvas">{entered ? view : <Gateway onEnter={() => setEntered(true)} />}{settings && <SettingsSheet onClose={() => setSettings(false)} />}</div> }
