'use client'

import { FormEvent, useEffect, useState } from 'react'
import { ArrowLeft, ArrowUp, Check, ChevronRight, Copy, KeyRound, Menu, MoreHorizontal, Paperclip, Phone, QrCode, Search, Send, Settings, Sparkles, UserRound, Video, Wallet, X } from 'lucide-react'

type Contact = { name: string; alias: string; snippet: string; time: string; online: boolean; emoji: string }
type View = 'ONBOARDING' | 'CHAT_LIST' | 'ACTIVE_CHAT' | 'PROFILE_MENU'

const contacts: Contact[] = [
  { name: 'Morgan Lee', alias: '@morgan', snippet: 'The violet room is ready.', time: '09:42', online: true, emoji: 'M' },
  { name: 'Sage Chen', alias: '@sage', snippet: 'Sending you the notes now.', time: 'Yesterday', online: true, emoji: 'S' },
  { name: 'Riley Park', alias: '@riley', snippet: 'That sounds like a plan.', time: 'Tue', online: false, emoji: 'R' },
  { name: 'Noah Williams', alias: '@noah', snippet: 'Let’s talk after sunset.', time: 'Mon', online: true, emoji: 'N' },
]
const stories = [{ name: 'Morgan', emoji: 'M', active: true }, { name: 'Sage', emoji: 'S', active: true }, { name: 'Riley', emoji: 'R', active: false }, { name: 'Noah', emoji: 'N', active: true }]
const seed = ['velvet','orbit','cinder','lumen','quiet','violet','harbor','north','echo','silver','morrow','atlas']

function Mark() { return <span className="brand-mark"><Sparkles /></span> }
function Tap({ className = '', ...props }: React.ButtonHTMLAttributes<HTMLButtonElement>) { return <button className={`tap ${className}`} {...props} /> }
function Toast({ text }: { text: string }) { return <div className="toast" role="status"><Check /> {text}</div> }

function Gateway({ onEnter }: { onEnter: () => void }) {
  const [loading, setLoading] = useState(false); const [generated, setGenerated] = useState(false); const [revealed, setRevealed] = useState(false)
  function generate() { setLoading(true); window.setTimeout(() => { setLoading(false); setGenerated(true) }, 1500) }
  return <main className="gateway"><div className="gateway-art"><div className="gateway-ring" /><div className="gateway-mark"><Mark /></div></div><span className="eyebrow">PRIVATE MESSENGER / 01</span><h1>Find your people.<br /><em>Keep your space.</em></h1><p className="gateway-copy">Nexus is a quiet, cryptographic room for the people who matter. No feeds. No noise. Just presence.</p>{!generated ? <Tap className="primary-action" onClick={generate} disabled={loading}>{loading ? <span className="spinner" /> : <KeyRound />} {loading ? 'Generating local identity...' : 'Generate cryptographic profile identity'} <ChevronRight /></Tap> : <div className="identity-card"><div className="identity-card-head"><span>YOUR PRIVATE SEED</span><Tap onClick={() => setRevealed(!revealed)}>{revealed ? 'Mask' : 'Reveal'}</Tap></div><div className="seed-words">{seed.map((word, i) => <span key={word}>{revealed ? `${i + 1}. ${word}` : `${String(i + 1).padStart(2,'0')} •••••`}</span>)}</div><Tap className="primary-action" onClick={onEnter}>Enter Nexus Network <ArrowUp /></Tap></div>}<small className="gateway-note">Your identity is generated on-device and never stored by Nexus.</small></main>
}

function ProfileDrawer({ avatar, setAvatar, onClose, onToast }: { avatar: string | null; setAvatar: (value: string) => void; onClose: () => void; onToast: (text: string) => void }) {
  const wallet = '0x7a9C...4F2B';
  function upload(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (file) setAvatar(URL.createObjectURL(file)) }
  async function copyAddress() { await navigator.clipboard?.writeText('0x7a9C91eA2d7F8B2c4F2B'); onToast('Wallet address copied') }
  return <div className="drawer-backdrop" onClick={onClose}><aside className="profile-drawer" onClick={(e) => e.stopPropagation()}><header className="drawer-header"><div><span className="eyebrow">NEXUS / PROFILE</span><h2>Your space</h2></div><Tap className="nav-icon" onClick={onClose} aria-label="Close profile menu"><X /></Tap></header><label className="avatar-upload"><input type="file" accept="image/*" onChange={upload} />{avatar ? <img src={avatar} alt="Uploaded profile avatar" /> : <UserRound />}<span>Change avatar</span></label><section className="wallet-card"><div className="wallet-title"><Wallet /><span>NEXUS CRYPTO WALLET</span><small>LIVE</small></div><strong>$1,250.00</strong><p>0.5 ETH · available balance</p><div className="wallet-address"><code>{wallet}</code><Tap onClick={copyAddress} aria-label="Copy wallet address"><Copy /></Tap></div><div className="wallet-actions"><Tap onClick={() => onToast('Send flow ready')}><Send /> Send</Tap><Tap onClick={() => onToast('Receive address ready')}><QrCode /> Receive</Tap><Tap onClick={() => onToast('Swap flow ready')}><Sparkles /> Swap</Tap></div></section><section className="drawer-links"><Tap onClick={() => onToast('Privacy center opened')}><KeyRound /><span><b>Privacy center</b><small>Identity capsule and encryption</small></span><ChevronRight /></Tap><Tap onClick={() => onToast('Notifications are enabled')}><Sparkles /><span><b>Notifications</b><small>Quiet hours and mentions</small></span><ChevronRight /></Tap><Tap onClick={() => onToast('Settings saved locally')}><Settings /><span><b>Preferences</b><small>Appearance and language</small></span><ChevronRight /></Tap></section></aside></div>
}

function Directory({ onSelect, onProfile }: { onSelect: (contact: Contact) => void; onProfile: () => void }) { return <main className="messenger-shell"><header className="messenger-header"><Tap className="nav-icon" aria-label="Open menu"><Menu /></Tap><div className="brand-lockup"><Mark /><b>NEXUS</b></div><div className="header-actions"><Tap className="nav-icon" aria-label="More options"><MoreHorizontal /></Tap><Tap className="nav-icon profile-button" onClick={onProfile} aria-label="Open profile wallet"><UserRound /></Tap></div></header><div className="directory-head"><div><span className="eyebrow">PRIVATE NETWORK</span><h1>Your people<span>.</span></h1></div><Tap className="profile-orb" onClick={onProfile} aria-label="Open your profile"><UserRound /></Tap></div><div className="search-bar"><Search /><input placeholder="Search your network" /></div><section className="stories"><div className="section-label"><span>Stories</span><Tap>View all</Tap></div><div className="story-row">{stories.map((story) => <Tap className="story" key={story.name}><span className={`story-avatar ${story.active ? 'story-active' : ''}`}>{story.emoji}</span><small>{story.name}</small></Tap>)}</div></section><section className="contacts"><div className="section-label"><span>Conversations</span><span className="muted">{contacts.length} people</span></div>{contacts.map((contact) => <Tap className="contact-row" key={contact.name} onClick={() => onSelect(contact)}><span className={`contact-avatar ${contact.online ? 'online' : ''}`}>{contact.emoji}</span><span className="contact-copy"><b>{contact.name}</b><small>{contact.alias} · {contact.snippet}</small></span><span className="contact-meta"><small>{contact.time}</small><ChevronRight /></span></Tap>)}</section><footer className="network-footer"><span className="online-dot" /> Encrypted network <span>·</span> 12 peers</footer></main> }

function Chat({ contact, onBack, onProfile }: { contact: Contact; onBack: () => void; onProfile: () => void }) { const [draft, setDraft] = useState(''); const [messages, setMessages] = useState(['Good morning. I left a little space here for you.', 'I like that. Let’s make today feel intentional.']); function submit(e: FormEvent) { e.preventDefault(); const message = draft.trim(); if (!message) return; setMessages((current) => [...current, message]); setDraft('') } return <main className="messenger-shell chat-shell"><header className="chat-header"><Tap className="nav-icon" onClick={onBack} aria-label="Back"><ArrowLeft /></Tap><span className={`chat-avatar ${contact.online ? 'online' : ''}`}>{contact.emoji}</span><div className="chat-title"><b>{contact.name}</b><small>{contact.online ? 'online now' : 'last seen recently'}</small></div><div className="header-actions"><Tap className="nav-icon" aria-label="Start video call"><Video /></Tap><Tap className="nav-icon" onClick={onProfile} aria-label="Open profile"><MoreHorizontal /></Tap></div></header><div className="chat-transcript"><div className="date-stamp"><span /> TODAY <span /></div>{messages.map((message, i) => <div className={`chat-message ${i % 2 ? 'mine' : ''}`} key={`${message}-${i}`}><p>{message}</p><small>{i % 2 ? '09:41 · Sent' : '09:40'}</small></div>)}<div className="typing"><span /> {contact.name} is in the room</div></div><div className="chat-composer-wrap"><div className="chat-tools"><Tap aria-label="Attach file"><Paperclip /></Tap><span>Private message</span><Tap aria-label="Start call"><Phone /></Tap></div><form className="chat-composer" onSubmit={submit}><input value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="Say something true..." /><Tap className="send-orb" aria-label="Send message"><ArrowUp /></Tap></form><small className="composer-note">End-to-end encrypted · ephemeral by default</small></div></main> }

export default function Page() { const [view, setView] = useState<View>('ONBOARDING'); const [selected, setSelected] = useState<Contact | null>(null); const [avatar, setAvatar] = useState<string | null>(null); const [toast, setToast] = useState(''); useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(''), 2200); return () => window.clearTimeout(timer) }, [toast]); function showToast(text: string) { setToast(text) } return <div className="app-canvas">{view === 'ONBOARDING' && <Gateway onEnter={() => setView('CHAT_LIST')} />}{view === 'CHAT_LIST' && <Directory onSelect={(contact) => { setSelected(contact); setView('ACTIVE_CHAT') }} onProfile={() => setView('PROFILE_MENU')} />}{view === 'ACTIVE_CHAT' && selected && <Chat contact={selected} onBack={() => setView('CHAT_LIST')} onProfile={() => setView('PROFILE_MENU')} />}{view === 'PROFILE_MENU' && <Directory onSelect={(contact) => { setSelected(contact); setView('ACTIVE_CHAT') }} onProfile={() => setView('PROFILE_MENU')} />} {view === 'PROFILE_MENU' && <ProfileDrawer avatar={avatar} setAvatar={setAvatar} onClose={() => setView(selected ? 'ACTIVE_CHAT' : 'CHAT_LIST')} onToast={showToast} />}{toast && <Toast text={toast} />}</div> }
